server:
  port: 8080

app:
  s3:
    bucket: YOUR_BUCKET_NAME
    region: us-east-1
    # endpoint: http://localhost:4566  # Uncomment for Localstack

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB